name: CI Validation (Push)

on:
  push:
    branches:
      - 'feature/*' # Solo ramas de trabajo
    tags-ignore:
      - '**' # Requisito: que no se dispare por tags

jobs:
  validate-code:
    uses: bapp86/central-templates/.github/workflows/reusable-pipeline.yml@main
    with:
      should_push: false
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
